version: '3.9'

services:
  telegram-bot:
    build: .
    volumes:
      - /Users/levstremilov/Downloads/bot_rent_119:/app
    depends_on:
      - sqlite-db

  sqlite-db:
    image: tiangolo/uwsgi-nginx-flask:python3.9
    volumes:
      - .//Users/levstremilov/Downloads/bot_rent_119/orderDatabase.db:/app/db
    environment:
      SQLITE_DATABASE_URI: sqlite:///db/goldenLike.db